sonar.projectKey=t3-template
sonar.projectName=T3 Template
sonar.host.url=https://sonar.chundev.com

# Source
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/*.config.*,**/generated/**

# Language
sonar.language=ts
sonar.typescript.tsconfigPaths=tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8
